import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {server} from './preview.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),evidence=path.join(root,'docs/evidence');
fs.mkdirSync(path.join(evidence,'after'),{recursive:true});
const routes=JSON.parse(fs.readFileSync(path.join(root,'tools/routes.json'))),results=[],errors=[],requests=[];
const app=server();await new Promise(r=>app.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.address().port}`;
const browser=await chromium.launch({headless:true,channel:'chrome'});
function record(name,details){results.push({name,status:'pass',details});console.log('PASS',name);}
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 const links=new Set(),crawl=[];
 for(const route of routes){const r=await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(r.status(),200);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('html').getAttribute('lang'),'es-PY');assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),'https://agroveterinaria.com.py'+route);assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,nofollow');assert.ok((await page.title()).length>10);assert.ok((await page.locator('meta[name=description]').getAttribute('content')).length>40);for(const schema of await page.locator('script[type="application/ld+json"]').allTextContents()){const data=JSON.parse(schema);assert.ok(data.every(s=>!['Store','Product','LocalBusiness'].includes(s['@type'])));}for(const href of await page.locator('a').evaluateAll(a=>a.map(x=>x.getAttribute('href')))){assert.ok(!href?.startsWith('tel:')&&!href?.includes('wa.me'));if(href?.startsWith('/'))links.add(href);}assert.equal(await page.locator('form[action]').count(),0);assert.equal(await page.locator('img').evaluateAll(a=>a.filter(i=>!i.complete||i.naturalWidth===0).length),0);crawl.push({route,status:r.status(),title:await page.title()});}
 record('10 public routes: metadata, one H1, truthful schema, local images',crawl);
 for(const href of links){const response=await context.request.get(base+href);assert.equal(response.status(),200,href);}record('Internal links resolve',`${links.size} distinct paths including query links`);
 const robots=await context.request.get(base+'/robots.txt');assert.equal(robots.status(),200);assert.match(await robots.text(),/Sitemap: https:\/\/agroveterinaria.com.py\/sitemap.xml/);const sm=await context.request.get(base+'/sitemap.xml');assert.equal(sm.status(),200);assert.equal((await sm.text()).match(/<loc>/g).length,routes.length);record('robots.txt and sitemap',`${routes.length} canonical URLs; staging retains noindex`);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});for(const route of routes){await page.goto(base+route,{waitUntil:'networkidle'});const over=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(over,false,`${route} at ${width}`);if(['/','/servicios/alimentos-balanceados/','/contacto/'].includes(route)){const name=route==='/'?'home':route==='/contacto/'?'contacto':'alimentos';await page.screenshot({path:path.join(evidence,'after',`${name}-${width}.png`),fullPage:true});await page.screenshot({path:path.join(evidence,'after',`${name}-${width}-top.png`)});}}}record('Responsive widths and screenshots','30 page/width combinations at 1440, 390 and 320; zero horizontal overflow');
 await page.goto(base+'/');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Ir al contenido');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#main');await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');assert.ok(await page.locator('.main-nav').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.className),'menu-toggle');record('Keyboard navigation','Skip link, menu toggle and Escape/focus return');
 await page.goto(base+'/productos/?necesidad=mascotas');assert.equal(await page.locator('[data-audience]:visible').count(),3);await page.getByRole('button',{name:'Producción',exact:true}).click();assert.equal(await page.locator('[data-audience]:visible').count(),5);await page.getByRole('button',{name:'Todas',exact:true}).click();assert.equal(await page.locator('[data-audience]:visible').count(),5);record('Audience filters','Mascotas=3; producción=5; all=5');
 await page.goto(base+'/contacto/?categoria=vacunas');assert.equal(await page.locator('[name=categoria]').inputValue(),'vacunas');assert.equal(await page.locator('[name=especie]').inputValue(),'Producción · bovinos');assert.ok(await page.locator('#copy-list').isDisabled());await page.locator('[name=producto]').fill('   ');await page.locator('#add-item').click();assert.equal(await page.locator('#items li').count(),0);
 const payload='<img src=x onerror="window.injected=true">';await page.locator('[name=producto]').fill(payload);await page.locator('[name=cantidad]').fill('2 unidades (prueba)');await page.locator('#add-item').click();assert.equal(await page.locator('#items li').count(),1);assert.equal(await page.locator('#items img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);assert.match(await page.locator('#summary').inputValue(),/Vacunas para ganado/);assert.match(await page.locator('#summary').inputValue(),/No|no/);record('List validation and injection safety','Whitespace rejected, HTML rendered as text, human category labels');
 await page.locator('#copy-list').click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),await page.locator('#summary').inputValue());const downloadPromise=page.waitForEvent('download');await page.locator('#download-list').click();const download=await downloadPromise;const downloaded=path.join(evidence,'synthetic-list.txt');await download.saveAs(downloaded);assert.equal(fs.readFileSync(downloaded,'utf8'),await page.locator('#summary').inputValue());record('Copy and download','Synthetic data; clipboard and UTF-8 .txt match summary');
 await page.getByRole('button',{name:'Quitar '+payload,exact:true}).click();assert.equal(await page.locator('#items li').count(),0);for(let i=0;i<21;i++){await page.locator('[name=producto]').fill('Producto sintético '+i);await page.locator('#add-item').click();}assert.equal(await page.locator('#items li').count(),20);assert.match(await page.locator('#list-status').innerText(),/20 productos/);await page.locator('#clear-list').click();assert.equal(await page.locator('#items li').count(),0);assert.ok(await page.locator('#copy-list').isDisabled());await page.locator('[name=producto]').fill('Producto de prueba');await page.locator('#add-item').click();await page.reload();assert.equal(await page.locator('#items li').count(),0);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);record('List lifecycle','Remove, 20-item limit, reset and no persistence');
 assert.equal(requests.filter(r=>r.method!=='GET').length,0);assert.ok(requests.every(r=>r.url.startsWith(base)));assert.equal(errors.length,0,errors.join('\n'));record('No outbound leads or runtime errors','Only local GET requests; no analytics, storage, sending endpoints or browser errors');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const np=await nojs.newPage();await np.goto(base+'/');assert.ok(await np.locator('.main-nav').isVisible());await np.goto(base+'/productos/');assert.equal(await np.locator('[data-audience]:visible').count(),5);await np.goto(base+'/contacto/');assert.ok(await np.getByText('Prepará tu lista sin esta herramienta').isVisible());record('JavaScript-disabled fallback','Navigation, categories and manual list instructions remain visible');await nojs.close();
 for(const route of ['/missing-audit-page/','/.env','/package.json','/STEP-0-RECON.md','/docs/reference/index.html','/contacto.php']){const r=await context.request.get(base+route);assert.equal(r.status(),404,route);}assert.equal((await context.request.post(base+'/contacto/')).status(),405);assert.equal((await context.request.get(base+'/servicios/alimentos-balanceados',{maxRedirects:0})).status(),301);record('404, private paths and method handling','Unknown/private paths=404, POST=405, missing trailing slash=301');
 const publicFiles=[];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())walk(file);else publicFiles.push(path.relative(path.join(root,'public'),file));}}walk(path.join(root,'public'));assert.ok(publicFiles.every(f=>/\.(html|css|js|svg|webp|xml|txt)$/.test(f)||f==='.htaccess'));for(const f of publicFiles.filter(f=>!f.endsWith('.webp'))){const text=fs.readFileSync(path.join(root,'public',f),'utf8');assert.ok(!/595981000000|api[_-]?key\s*[:=]|CRM_TOKEN|ghp_[A-Za-z0-9]|BEGIN PRIVATE KEY/i.test(text),f);}record('Release allowlist and placeholder/secret scan',`${publicFiles.length} public files; no source, docs, credentials or placeholder phone`);
 fs.writeFileSync(path.join(evidence,'test-results.json'),JSON.stringify({date:'2026-10-05',browser:await browser.version(),results,errors,publicFiles},null,2));
}catch(e){fs.writeFileSync(path.join(evidence,'test-failure.json'),JSON.stringify({results,errors,error:e.stack},null,2));throw e;}finally{await browser.close();await new Promise(r=>app.close(r));}
